### ISSUE TITLE
Do we have to rely on PKG-INFO ?

### ISSUE THREAD

**Issue by asmodehn** [mikepurvis/catkin_tools_python#7]
After trying it out, I realized that create_python_package_xmls extracts information from PKG-INFO.

I see two potential issues with this strategy : 

- In a workspace, I can checkout a (python) repo, and try to build it (to get my ros/catkin package to 
depend on it for example). But many python repo do not include PKG-INFO ( they are not the output of sdist ).

- After releasing with bloom, the release repo doesn't have a PKG-INFO, which means one cannot generate package.xml on the fly when building a deb package. => A package.xml need to be maintained in the release repo for a thirdparty package

So I am wondering if there would be another place where we could extract information from ?
Or is there a way I could fix the issues I listed previously ?

My current flow to mutate a pip package into a ros package with catkin_pip is : 

- getting the source of the package (as in upstream, not the sdist output),
- bloom releasing that,
- CMakeLists and package.xml are patches in the release repo, and get automatically added.
- rosdistro PR for the buildfarm to make the package.

Does this mean I should change that workflow to be able to get the PKG-INFO and automatically generate the package.xml in the release repo ? I am trying to minimize maintenance on the release repo.

**Comment by mikepurvis** [comment]
I've added some more notes to the README to further clarify a few points:

- This tool doesn't help you out with bloom or creating releases to ros_buildfarm— it's only about local development and bundle style whole-workspace deployment.
- The use of PKG-INFO is purely for convenience of a demonstration. In most scenarios where this was being used, I'd anticipate that the package.xml would be generated either into a mirror of the upstream, or maintained directly within the source (if it's your own source).

Note as well that there are a lot of inconsistencies with packages on PyPI— for example empy still uses distutils and doesn't even _have_ a `PKG-INFO`, other packages have zip archives instead of tarballs, there are no conventions enforced around naming or version numbers. Basically it's a big mess.

**Comment by asmodehn** [comment]
Yes I realized that PyPI mess, which is why I prefer to generate the ros package from the source, and hope that ultimately the sources will evolve to match pypa guidelines...

For catkin, I think OSRF should come up with a cookiecutter template that is supported, I think it would help a lot to make ROS sources consistent, as well as helping beginners.

But then I have no way (afaik) to get the package information (unless I wrap setuptools - and maintain that wrapper - which I d like to avoid), which is the reason why I currently cannot generate the package.xml. I'd like to find a way though...

I have been thinking about using setuptools command line arguments, Ex : 
```
alexv@AlexV-Linux:~/Projects/ros_pyros_ws/src/pyros_schemas$ python setup.py --name
pyros_schemas
alexv@AlexV-Linux:~/Projects/ros_pyros_ws/src/pyros_schemas$ python setup.py --description
Pyros messages and services definition
alexv@AlexV-Linux:~/Projects/ros_pyros_ws/src/pyros_schemas$ python setup.py --maintainer
UNKNOWN
```
Did you try that approach ?
